# Generated by Django 5.0.6 on 2024-05-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_coach_created_at_coach_is_deleted_coach_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
