# Generated by Django 5.0.6 on 2024-05-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchtype', '0002_alter_matchtype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchtype',
            name='gender',
            field=models.CharField(choices=[('male', '남자'), ('female', '여자'), ('mix', '혼성')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='matchtype',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matchtype',
            name='type',
            field=models.CharField(choices=[('single', '단식'), ('duo', '복식'), ('team', '팀')], max_length=6, null=True),
        ),
    ]
