# Generated by Django 5.0.6 on 2024-05-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchtype', '0003_alter_matchtype_gender_alter_matchtype_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchtype',
            name='gender',
            field=models.CharField(choices=[('male', '남자'), ('female', '여자'), ('mix', '혼성'), ('team', '팀')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='matchtype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
