# Generated by Django 5.0.6 on 2024-05-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchtype', '0004_alter_matchtype_gender_alter_matchtype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchtype',
            name='type',
            field=models.CharField(choices=[('single', '단식'), ('double', '복식'), ('team', '팀')], max_length=6, null=True),
        ),
    ]
