# Generated by Django 5.0.6 on 2024-05-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchtype', '0005_alter_matchtype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchtype',
            name='gender',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성'), ('mix', '혼성'), ('team', '팀')], max_length=6, null=True),
        ),
    ]
