# Generated by Django 5.0.4 on 2024-05-05 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='image_url',
        ),
    ]
