# Generated by Django 5.0.5 on 2024-05-08 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='image_url',
        ),
    ]
