# Generated by Django 5.0.6 on 2024-05-17 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0009_competition_max_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantInfo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('un_paid', '입금 전'), ('paid', '입금확인'), ('canceled', '취소')], max_length=15, null=True)),
                ('expired_date', models.DateTimeField(null=True)),
                ('is_waiting', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='competition.competition')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
