# Generated by Django 5.0.6 on 2024-05-17 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='applicantinfo',
            table='applicant_info',
        ),
    ]
