# Generated by Django 5.0.6 on 2024-05-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_info', '0002_alter_applicantinfo_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantinfo',
            name='status',
            field=models.CharField(choices=[('un_paid', '입금 전'), ('paid', '입금확인'), ('canceled', '취소')], default='un_paid', max_length=15),
        ),
    ]
