# Generated by Django 5.0.6 on 2024-05-21 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_info', '0004_alter_applicantinfo_competition'),
        ('competition', '0012_competition_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantinfo',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='competition.competition'),
        ),
    ]
