# Generated by Django 5.0.6 on 2024-05-27 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_info', '0006_alter_applicantinfo_is_waiting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantinfo',
            old_name='is_waiting',
            new_name='waiting_number',
        ),
    ]
