# Generated by Django 5.0.6 on 2024-05-26 19:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_alter_club_id'),
        ('club_applicant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClubApplication',
            new_name='ClubApplicant',
        ),
    ]
