# Generated by Django 5.0.6 on 2024-05-26 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_applicant', '0002_rename_clubapplication_clubapplicant'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clubapplicant',
            table='club_applicant',
        ),
    ]
