# Generated by Django 5.0.6 on 2025-03-26 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('match_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=6, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('match_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='match_type.matchtype')),
            ],
            options={
                'db_table': 'tier',
            },
        ),
    ]
