# Generated by Django 5.0.6 on 2024-05-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tier', '0002_tier_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
