# Generated by Django 5.0.6 on 2024-05-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tier', '0003_alter_tier_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='level',
        ),
        migrations.AlterField(
            model_name='tier',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
