# Generated by Django 5.0.4 on 2024-05-01 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
        ('image_url', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='club.club')),
                ('image_url', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='image_url.imageurl')),
            ],
            options={
                'db_table': 'team',
            },
        ),
    ]
