# Generated by Django 5.0.5 on 2024-05-08 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='image_url',
        ),
    ]
