# Generated by Django 5.0.5 on 2024-05-08 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_url', '0010_remove_imageurl_content_type_and_more'),
        ('team', '0004_remove_team_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='image_url.imageurl'),
        ),
    ]
