# Generated by Django 5.0.4 on 2024-05-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, max_length=6, null=True)),
                ('start_date', models.DateTimeField(blank=True, db_column='startDate', null=True)),
                ('end_date', models.DateTimeField(blank=True, db_column='endDate', null=True)),
                ('round', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('rule', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('code', models.BigIntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('fee', models.IntegerField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, db_column='bankName', max_length=30, null=True)),
                ('bank_account_number', models.IntegerField(blank=True, db_column='bankAccountNumber', null=True)),
                ('bank_account_name', models.CharField(blank=True, db_column='bankAccountName', max_length=30, null=True)),
                ('site_link', models.TextField(blank=True, db_column='siteLink', null=True)),
                ('feedback', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'competition',
            },
        ),
    ]
