# Generated by Django 5.0.6 on 2025-03-24 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image_url', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, max_length=6, null=True)),
                ('start_date', models.DateTimeField(blank=True, db_column='startDate', null=True)),
                ('end_date', models.DateTimeField(blank=True, db_column='endDate', null=True)),
                ('round', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('rule', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('code', models.BigIntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('fee', models.IntegerField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, db_column='bankName', max_length=30, null=True)),
                ('bank_account_number', models.IntegerField(blank=True, db_column='bankAccountNumber', null=True)),
                ('bank_account_name', models.CharField(blank=True, db_column='bankAccountName', max_length=30, null=True)),
                ('site_link', models.TextField(blank=True, db_column='siteLink', null=True)),
                ('feedback', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='image_url.imageurl')),
            ],
            options={
                'db_table': 'competition',
            },
        ),
    ]
