# Generated by Django 5.0.6 on 2024-05-14 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_alter_competition_id'),
        ('matchtype', '0003_alter_matchtype_gender_alter_matchtype_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='status',
        ),
        migrations.AddField(
            model_name='competition',
            name='match_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='matchtype.matchtype'),
            preserve_default=False,
        ),
    ]
