# Generated by Django 5.0.6 on 2024-05-15 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_remove_competition_status_competition_match_type'),
        ('tier', '0004_remove_tier_level_alter_tier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='tier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tier.tier'),
            preserve_default=False,
        ),
    ]
