# Generated by Django 5.0.6 on 2024-05-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_competition_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='max_participants',
            field=models.IntegerField(default=100),
        ),
    ]
