# Generated by Django 5.0.6 on 2024-05-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0010_alter_competition_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='deposit_date',
            field=models.IntegerField(help_text='입금기한_신청기준 몇일', null=True),
        ),
    ]
