# Generated by Django 5.0.6 on 2024-05-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0011_competition_deposit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('before', 'before'), ('during', 'during'), ('ended', 'ended')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
