# Generated by Django 5.0.6 on 2024-05-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0012_competition_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='deposit_refund_policy',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
