# Generated by Django 5.0.6 on 2024-05-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0013_competition_deposit_refund_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='code',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
    ]
