# Generated by Django 5.0.6 on 2024-05-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0014_alter_competition_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='round',
            new_name='total_rounds',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='feedback',
        ),
        migrations.AddField(
            model_name='competition',
            name='total_sets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
