# Generated by Django 5.0.4 on 2024-05-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageurl',
            name='image_url',
            field=models.URLField(blank=True, db_column='imageUrl', null=True),
        ),
    ]
