# Generated by Django 5.0.4 on 2024-05-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_url', '0002_alter_imageurl_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageurl',
            name='description',
        ),
        migrations.RemoveField(
            model_name='imageurl',
            name='image_url',
        ),
        migrations.AddField(
            model_name='imageurl',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='imageurl',
            name='image_type',
            field=models.CharField(choices=[('club', '클럽이미지'), ('user', '유저이미지'), ('team', '팀이미지'), ('competition', '대회이미지')], default='user', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='imageurl',
            table=None,
        ),
    ]
