# Generated by Django 5.0.4 on 2024-05-05 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_remove_club_image_url'),
        ('competition', '0001_initial'),
        ('image_url', '0003_remove_imageurl_description_and_more'),
        ('team', '0002_remove_team_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imageurl',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='club.club'),
        ),
        migrations.AddField(
            model_name='imageurl',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='competition.competition'),
        ),
        migrations.AddField(
            model_name='imageurl',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='team.team'),
        ),
        migrations.AddField(
            model_name='imageurl',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imageurl',
            name='image_type',
            field=models.CharField(choices=[('user', '유저이미지'), ('club', '클럽이미지'), ('team', '팀이미지'), ('competition', '대회이미지')], max_length=30),
        ),
    ]
