# Generated by Django 5.0.4 on 2024-05-05 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_url', '0004_imageurl_club_imageurl_competition_imageurl_team_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imageurl',
            table='image_url',
        ),
    ]
