# Generated by Django 5.0.5 on 2024-05-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_url', '0005_alter_imageurl_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageurl',
            name='club',
        ),
        migrations.RemoveField(
            model_name='imageurl',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='imageurl',
            name='image_type',
        ),
        migrations.RemoveField(
            model_name='imageurl',
            name='team',
        ),
        migrations.RemoveField(
            model_name='imageurl',
            name='user',
        ),
        migrations.AddField(
            model_name='imageurl',
            name='extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='imageurl',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
