# Generated by Django 5.0.5 on 2024-05-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_url', '0006_remove_imageurl_club_remove_imageurl_competition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageurl',
            old_name='image',
            new_name='image_url',
        ),
    ]
