# Generated by Django 5.0.5 on 2024-05-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_url', '0007_rename_image_imageurl_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageurl',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
