# Generated by Django 5.0.5 on 2024-05-08 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('image_url', '0008_alter_imageurl_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageurl',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='imageurl',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
