# Generated by Django 5.0.5 on 2024-05-08 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_url', '0009_imageurl_content_type_imageurl_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageurl',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='imageurl',
            name='object_id',
        ),
    ]
