# Generated by Django 5.0.6 on 2024-05-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_url', '0010_remove_imageurl_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageurl',
            name='image_url',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to=''),
        ),
    ]
