# Generated by Django 5.0.6 on 2025-03-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(blank=True, choices=[('male', '남성'), ('female', '여성')], max_length=6, null=True)),
                ('type', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'match_type',
            },
        ),
    ]
