# Generated by Django 5.0.6 on 2024-05-17 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_alter_applicant_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='partner',
        ),
    ]
