# Generated by Django 5.0.6 on 2024-05-19 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_remove_applicant_partner'),
        ('applicant_info', '0003_alter_applicantinfo_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='applicant',
        ),
        migrations.AddField(
            model_name='applicant',
            name='applicant_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_infos', to='applicant_info.applicantinfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to=settings.AUTH_USER_MODEL),
        ),
    ]
