# Generated by Django 5.0.6 on 2024-05-20 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_remove_applicant_applicant_applicant_applicant_info_and_more'),
        ('applicant_info', '0003_alter_applicantinfo_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='applicant_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant_info.applicantinfo'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
